---
title: "Data Manipulation"
output: github_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
```

This document will show how to *manipulate* data. 

Import the two datasets that we are going to manipulate.

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", "", "."))

litters_df = janitor::clean_names(litters_df)

pups_df = 
  read_csv("data/FAS_pups.csv", na=c("NA", "", "."))

pups_df = janitor::clean_names(pups_df)
```

## `select`

Use `select` to select variables 

```{r}
select(litters_df, group, litter_number, gd0_weight)
```

```{r}
select(litters_df, group:gd18_weight)
```

```{r}
select(litters_df, -pups_survive)
```

```{r}
select(litters_df, -(group:gd18_weight))
```

```{r}
select(litters_df, starts_with("gd"))

select(litters_df, contains("pups"))
```

```{r}
select(litters_df, GROUP = group)

rename(litters_df, GROUP = group)

select(litters_df, litter_number, gd0_weight, everything())

relocate(litters_df, litter_number, gd0_weight)
```


```{r}
select(pups_df, litter_number, sex, pd_ears)
```




## `filter`
filtering out rows. 

```{r}
filter(litters_df, gd_of_birth == 20)
filter(litters_df, gd_of_birth == 19)
```

```{r}
filter(litters_df, pups_born_alive > 8)
filter(litters_df, pups_born_alive >= 8)
```

```{r}
filter(litters_df, pups_born_alive != 9)
```

```{r}
filter(litters_df, group == "Low8")
filter(litters_df, group %in% c("Low7", "Low8"))
```

```{r}
filter(litters_df, group %in% c("Low7", "Low8"), pups_born_alive ==8)
```

```{r}
drop_na(litters_df)

drop_na(litters_df, gd0_weight)
```

```{r}
filter(pups_df, sex == 1)
filter(pups_df, pd_walk < 11, sex == 2)
```



## `mutate`

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)

mutate(litters_df, sq_pups = pups_born_alive^2)

mutate(litters_df, group = str_to_lower(group))

mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
  )

```




## `arrange`

```{r}
arrange(litters_df, gd0_weight)

arrange(litters_df, desc(gd0_weight))

arrange(litters_df, pups_born_alive, gd0_weight)
```





## PIPING!!!!!

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", "", ".")) |>
  janitor::clean_names() |>
  select(-pups_born_alive) |>
  filter(group == "Con7") |>
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)
  )
```

Pipe with the thing is not the first argument. 

```{r}
read_csv("data/FAS_litters.csv", na = c("NA", "", ".")) |>
  janitor::clean_names() |>
  mutate()

```

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", "", ".")) |>
  janitor::clean_names() |>
  select(-pups_born_alive) |>
  filter(group == "Con7") |>
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)
  )
write_csv(litters_df, "data/cleaned_fas_litters.csv")
```


